name: AWS
on:
  push:
    paths:
      - 'aws/**'
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate
        uses: gardenbed/actions/terraform@main
        with:
          path: ./aws
          args: validate
