name: Google
on:
  push:
    paths:
      - 'google/**'
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: touch ./google/account.json
      - name: Validate
        uses: gardenbed/actions/terraform@main
        with:
          path: ./google
          args: validate
